### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/category_meta.json'

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/omni3d#3]
FileNotFoundError: [Errno 2] No such file or directory: 'configs/category_meta.json'

**Comment by garrickbrazil** [comment]
Can you give more details of what you were trying to run? Currently, the only supported application to run is the demo.py

**Comment by jinfagang** [comment]
@garrickbrazil Hi, am just runing the demo promot in readme. As you can see, your repo actually doesn't have this file, may I ask how can I obtain it? (I also didn't notice anywhere can download or gen this file)

**Comment by garrickbrazil** [comment]
The category_meta.json file is cached automatically through the the [PathHandler](https://github.com/facebookresearch/omni3d/blob/main/cubercnn/util/model_zoo.py#L11) similar to the other files, e.g., it is pulled from cubercnn://omni3d/category_meta.json automatically whenever its needed. 

Perhaps your issue is due to an inconsistency between the MODEL_ZOO files and the demo, which has since been corrected? We have verified that the updated demo.py detailed in the README runs as expected in fresh environments. Let me know how it goes.

**Comment by jinfagang** [comment]
@garrickbrazil Hi, I run into because I can not access cuberrcnn:// url, so I using local config file. How to acess that url in http?

**Comment by a-nau** [comment]
@jinfagang you can find the file here https://dl.fbaipublicfiles.com/cubercnn/omni3d/category_meta.json with the base url mapping from [here](https://github.com/facebookresearch/omni3d/blob/main/cubercnn/util/model_zoo.py#L12).

**Comment by jinfagang** [comment]
thank u!

**Comment by rebelmachina** [comment]
> @jinfagang you can find the file here https://dl.fbaipublicfiles.com/cubercnn/omni3d/category_meta.json with the base url mapping from [here](https://github.com/facebookresearch/omni3d/blob/main/cubercnn/util/model_zoo.py#L12).

I can't download category_meta.json from `https://dl.fbaipublicfiles.com/cubercnn/omni3d/category_meta.json`, it says Access denied. 

Why isn't this file simply committed in the configs/ like the rest of the YAMLs ?
