### ISSUE TITLE
Maybe bug in evaluation

### ISSUE THREAD

**Issue by Lizhuoling** [facebookresearch/omni3d#33]
Hi, I first evaluate the provided checkpoint and get results as expected.
![image](https://user-images.githubusercontent.com/32482856/236674445-17a9e289-bac8-490d-a936-5b23d99e8e3b.png)
The detection results comprise the 2D detection and 3D detection parts. The problem is when I delete all 3D detection results and only submit the 2D detection results, the evaluation code still returns very promising 3D detection scores. What causes this?
![image](https://user-images.githubusercontent.com/32482856/236674512-8392def9-e66c-46cc-b29c-1d4653961caf.png)

**Comment by garrickbrazil** [comment]
Hello! Thank you for submitting this issue. I'll look into it over the next few days. I wonder if it's related to a caching issue? 

Can you elaborate on what you mean by "delete all 3D detection results"? My understanding is that the code shouldn't evaluate at all if the 3D fields have been deleted. (also, if you have any cached json files for the kitti_val detections to help my inspection, feel free to share, otherwise I'll reproduce.)

**Comment by Lizhuoling** [comment]
I simply delete the values corresponding to keys ['pred_bbox3D', 'pred_center_cam', 'pred_center_2D', 'pred_dimensions', 'pred_pose'] in the results. It is realized by the following code line109~line111 in rcnn3d.py:
![image](https://user-images.githubusercontent.com/32482856/236981676-62e1440f-a6c8-459f-a72d-da0ee90fe826.png)
The evaluation can still run normally. It seems because the  2D object detection results are provided, and all missed 3D object detection results (the values of deleted keys) will be padded as 1 automatically.

**Comment by brazgardian** [comment]
Thanks for the details! This is unexpected behavior in the evaluation which we've fixed by adding coplanar and nonzero checks for the cuboids, which may otherwise cause invalid (infinite) 3D IoUs. The issue should be fixed in the latest commit. Feel free to close if you find the issue is resolved as well.

**Comment by Lizhuoling** [comment]
Thanks for your effort! My problem has been addressed.

**Comment by star9988rr** [comment]
Hi, @Lizhuoling, can you reproduce the results of KITTI? What hyper-parameters do you use?
